### ISSUE TITLE
Admin role required?

### ISSUE THREAD

**Issue by jhertz99** [nicholaskillin/gloomhaven-battle-goals-bot-issues#1]
I've successfully added the bot to Discord (Thank you!) but it appears to require Admin permissions to mention the bot.   I would like to make the bot available to channel members without the Admin role.  Is that possible?  Thanks!

**Comment by nicholaskillin** [comment]
@jhertz99 I don't believe that the bot cares what roles the user has. I am an admin, so it's possible that it does require an admin and I just never noticed since I normally do this for my group. However, I glanced through the code again and it never checks the user's role before deciding what to do. So as long as the bot has access to the channel that your users are in, it should respond to anyone mentioning it in that channel.
